events { worker_connections 1024; }
http {
    log_format main '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                    '\$status \$body_bytes_sent "\$http_referer" '
                    '"\$http_user_agent" "\$upstream_addr"';
    access_log /var/log/nginx/access.log main;
    upstream static_sites {
        server website1:80 max_fails=3 fail_timeout=10s weight=3;
        server website2:80 max_fails=3 fail_timeout=10s weight=1;
        server website3:80 max_fails=3 fail_timeout=10s weight=1;
    }
    server {
       listen 80;
       
       location / {
          proxy_pass http://static_sites;
          proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Connection "";
          keepalive_timeout 60;
          add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
          expires off;
       }

       location /system/ {
            proxy_pass http://glances:61208/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            sub_filter_once off;
            sub_filter 'src="' 'src="/system/';
            sub_filter 'href="' 'href="/system/';
       }
       
       location /grafana/ {
           proxy_pass http://grafana:3000; 
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
       }

       location /static/ {
            proxy_pass http://glances:61208/static/;
       }

       location /nginx_status { stub_status; }
    }
}
